# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_one_cpp <- function(x) {
    .Call(`_mypackage_add_one_cpp`, x)
}

rcpparma_hello_world <- function() {
    .Call(`_mypackage_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_mypackage_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_mypackage_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_mypackage_rcpparma_bothproducts`, x)
}

